Migrate from ESLint to Biome
This commit migrates the project from ESLint to Biome for linting and formatting.

- Replaced ESLint with Biome for linting and formatting of JavaScript, TypeScript, and JSX files.
- Kept Prettier for formatting file types not supported by Biome, such as Markdown.
- Updated `package.json` scripts to use Biome and Prettier accordingly.
- Removed ESLint and its related dependencies.
- Updated `ATTRIBUTIONS.md` to reflect the new dependencies.
- Updated Gihub Actions

diff --git a/.github/workflows/tests.yaml b/.github/workflows/tests.yaml
--- a/.github/workflows/tests.yaml
+++ b/.github/workflows/tests.yaml
@@ -39,7 +39,17 @@ jobs:
       - name: Install npm deps
         run: npm ci
       - name: Prettier formatting
-        run: npm run prettier:check
+        run: |
+          npm run prettier:check || {
+            echo "::error::Prettier check failed. Please run `npm run prettier` locally.";
+            exit 1;
+          }
+      - name: Biome formatting
+        run: |
+          npm run biome:format:check || {
+            echo "::error::Biome check failed. Please run `npm run biome:format` locally.";
+            exit 1;
+          }
 
   lint:
     runs-on: ubuntu-latest
@@ -54,7 +64,11 @@ jobs:
       - name: Install npm deps
         run: npm ci
       - name: Lint
-        run: npm run lint
+        run: |
+          npm run lint:check || {
+            echo "::error::Lint check failed. Please run `npm run lint` locally.";
+            exit 1;
+          }
 
   unit-tests:
     runs-on: ubuntu-latest
